title: Testium
baseurl: ''
sourceUrl: https://github.com/testiumjs/testiumjs.github.io
sourceBranch: master
projectUrl: https://github.com/testiumjs/testium-core
copyright: "Copyright © 2015-2019 Groupon, Inc. All Rights Reserved."

exclude:
- README.md
- Gemfile
- Gemfile.lock

markdown: kramdown
sass:
  style: :compressed
defaults:
  - scope:
      path: ""
    values:
      category: docs

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
